# NAIVE BAYES

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/jennamacwe/Pendata/main/breast-cancer.csv')
dataset.head(5)

,age,mefalsepause,tumor-size,inv-falsedes,falsede-caps,deg-malig,breast,breast-quad,irradiat,class
0,40-49,premefalse,15-19,0-2,True,3,right,left_up,False,recurrence-events
1,50-59,ge40,15-19,0-2,False,1,right,central,False,false-recurrence-events
2,50-59,ge40,35-39,0-2,False,2,left,left_low,False,recurrence-events
3,40-49,premefalse,35-39,0-2,True,3,right,left_low,True,false-recurrence-events
4,40-49,premefalse,30-34,3-5,True,2,left,right_up,False,recurrence-events

In [ ]:
dataset.drop('breast-quad', axis=1, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
dataset['age']=enc.fit_transform(dataset['age'].values)
dataset['mefalsepause']=enc.fit_transform(dataset['mefalsepause'].values)
dataset['tumor-size']=enc.fit_transform(dataset['tumor-size'].values)
dataset['inv-falsedes']=enc.fit_transform(dataset['inv-falsedes'].values)
dataset['falsede-caps']=enc.fit_transform(dataset['falsede-caps'].values)
dataset['deg-malig']=enc.fit_transform(dataset['deg-malig'].values)
dataset['breast']=enc.fit_transform(dataset['breast'].values)
dataset['irradiat']=enc.fit_transform(dataset['irradiat'].values)
dataset['class']=enc.fit_transform(dataset['class'].values)
dataset.head(10)

,age,mefalsepause,tumor-size,inv-falsedes,falsede-caps,deg-malig,breast,irradiat,class
0,2,2,2,0,1,2,1,0,1
1,3,0,2,0,0,0,1,0,0
2,3,0,6,0,0,1,0,0,1
3,2,2,6,0,1,2,1,1,0
4,2,2,5,4,1,1,0,0,1
5,3,2,4,4,0,1,1,1,0
6,3,0,7,0,0,2,0,0,0
7,2,2,1,0,0,1,0,0,0
8,2,2,0,0,0,1,1,0,0
9,2,0,7,2,1,1,1,1,0

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           272 non-null    int64
 1   mefalsepause  272 non-null    int64
 2   tumor-size    272 non-null    int64
 3   inv-falsedes  272 non-null    int64
 4   falsede-caps  272 non-null    int64
 5   deg-malig     272 non-null    int64
 6   breast        272 non-null    int64
 7   irradiat      272 non-null    int64
 8   class         272 non-null    int64
dtypes: int64(9)
memory usage: 19.2 KB

In [ ]:
x=dataset.drop(["class"],axis=1)
x.head()

,age,mefalsepause,tumor-size,inv-falsedes,falsede-caps,deg-malig,breast,irradiat
0,2,2,2,0,1,2,1,0
1,3,0,2,0,0,0,1,0
2,3,0,6,0,0,1,0,0
3,2,2,6,0,1,2,1,1
4,2,2,5,4,1,1,0,0

In [ ]:
x_test = dataset.drop(["class"],axis=1)
x_test.head()

,age,mefalsepause,tumor-size,inv-falsedes,falsede-caps,deg-malig,breast,irradiat
0,2,2,2,0,1,2,1,0
1,3,0,2,0,0,0,1,0
2,3,0,6,0,0,1,0,0
3,2,2,6,0,1,2,1,1
4,2,2,5,4,1,1,0,0

In [ ]:
y=dataset["class"]
y.head()

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

In [ ]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()
nbtrain =modelnb.fit(x,y)
Y_predict = nbtrain.predict(x_test)
print("prediksi :", Y_predict)

prediksi : [0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0
 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1
 1 0 0 0 0 1 0 0 1 1 1 0 0]